FROM nginx:alpine

# Remove default config
RUN rm /etc/nginx/conf.d/default.conf

# Copy production config
COPY infra/docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Copy public assets from the project root (context)
COPY public /var/www/html/public

EXPOSE 80 443
